In [1]:
import numpy as np

def gauss_elimination_block_scheme(A, b):

    n = len(b)

    # Прямой ход (обнуление нижней части матрицы)
    for k in range(n):
        if A[k, k] == 0:
            for i in range(k+1, n):
                if A[i, k] != 0:
                    A[[k, i]] = A[[i, k]]
                    b[k], b[i] = b[i], b[k]
                    break
            else:
                raise ValueError("Система несовместна или имеет бесконечно много решений")

        for i in range(k+1, n):
            c = A[i, k] / A[k, k]
            for j in range(k, n):  
                A[i, j] -= c * A[k, j]
            b[i] -= c * b[k]  

    # Обратный ход (обратная подстановка)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        s = sum(A[i, j] * x[j] for j in range(i+1, n)) 
        x[i] = (b[i] - s) / A[i, i]  

    return x


A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], dtype=float)
b = np.array([8, -11, -3], dtype=float)


solution = gauss_elimination_block_scheme(A.copy(), b.copy())


print("\n✅ Решение системы:", solution)



✅ Решение системы: [ 2.  3. -1.]


In [8]:
import numpy as np

def gauss_elimination_block_scheme(A, b):

    n = len(b)

    for k in range(n):
        if A[k, k] == 0:
            for i in range(k+1, n):
                if A[i, k] != 0:
                    A[[k, i]] = A[[i, k]]
                    b[k], b[i] = b[i], b[k]
                    break
            else:
                raise ValueError("Система несовместна или имеет бесконечно много решений")

        for i in range(k+1, n):
            c = A[i, k] / A[k, k]
            for j in range(k, n):  
                A[i, j] -= c * A[k, j]
            b[i] -= c * b[k]  

    # Обратный ход (обратная подстановка)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        s = sum(A[i, j] * x[j] for j in range(i+1, n)) 
        x[i] = (b[i] - s) / A[i, i]  

    return x

def gauss_inverse_by_columns(A):

    n = len(A)
    A = np.array(A, dtype=float)
    E = np.eye(n, dtype=float)  
    A_inv = np.zeros_like(A)

    for i in range(n):
        b = E[:, i]
        A_inv[:, i] = gauss_elimination_block_scheme(A.copy(), b.copy())  # Решаем Ax = e_i

    return A_inv



np.random.seed(42)  
A = np.random.randint(1, 20, size=(7, 7))

print (A)
# A = np.array([
#     [2, 1, -1],
#     [-3, -1, 2],
#     [-2, 1, 2]
# ], dtype=float)

A_inv = gauss_inverse_by_columns(A)

# Вывод результата
print("\n✅ Обратная матрица A⁻¹:")
print(A_inv)


[[ 7 15 11  8  7 19 11]
 [11  4  8  3  2 12  6]
 [ 2  1 12 12 17 10 16]
 [15 15 19 12  3  5 19]
 [ 7  9  7 18  4 14 18]
 [ 9  2 15  7 12  8 15]
 [ 3 14 17  4 18  8  4]]

✅ Обратная матрица A⁻¹:
[[-0.12596776 -0.28620822 -0.82644577 -0.3673535   0.50543025  0.88922319
   0.21741278]
 [ 0.03050497 -0.28785932 -0.49416714 -0.19283618  0.26693853  0.51232311
   0.11810568]
 [ 0.040952    0.61656958  1.22454731  0.58148469 -0.73471536 -1.36764335
  -0.26283222]
 [-0.1271561   0.28725457  0.4104756   0.17429514 -0.11179587 -0.54278297
  -0.01248933]
 [-0.06690267 -0.38473905 -0.78528244 -0.39233801  0.47760992  0.90530262
   0.22169673]
 [ 0.06713014  0.18991264  0.33716511  0.11808146 -0.20060108 -0.36829488
  -0.09521359]
 [ 0.10762023 -0.33401104 -0.40594162 -0.1658052   0.17293611  0.55794691
  -0.00411132]]


In [10]:

A_check = np.dot(A, A_inv)

print(A_check)

[[ 1.00000000e+00  8.32667268e-16  3.88578059e-16  1.11022302e-16
  -1.19348975e-15  1.11022302e-16  2.11636264e-16]
 [-2.49800181e-16  1.00000000e+00  1.66533454e-15  1.11022302e-16
  -2.16493490e-15 -2.44249065e-15 -1.31838984e-16]
 [ 4.44089210e-16  0.00000000e+00  1.00000000e+00  0.00000000e+00
   8.88178420e-16  1.77635684e-15  1.11022302e-16]
 [-1.24900090e-16  2.16493490e-15  2.60902411e-15  1.00000000e+00
  -2.74780199e-15  1.11022302e-16 -9.36750677e-17]
 [-1.41553436e-15  1.44328993e-15  1.44328993e-15  1.22124533e-14
   1.00000000e+00 -1.35447209e-14  3.76781939e-15]
 [ 4.85722573e-16  1.05471187e-15 -1.16573418e-15 -4.99600361e-15
  -3.52495810e-15  1.00000000e+00 -7.18175519e-16]
 [ 1.16573418e-15 -6.66133815e-16 -1.11022302e-15 -7.77156117e-15
  -1.83186799e-14  5.77315973e-15  1.00000000e+00]]
